					<section class="copyright">
$if(page.property_is.("project.license").("Apache-2.0"))$
						<div>$page.properties.("project.name")$ is Open Source and available under the Apache 2 License.</div>
$endif$
						<p class="legal">
							&copy; 2011-$page.properties.("date.year")$ <a href="https://www.lightbend.com" target="_blank">Lightbend, Inc.</a> |
							<a href="https://www.lightbend.com/legal/licenses" target="_blank">Licenses</a> |
							<a href="https://www.lightbend.com/legal/terms" target="_blank">Terms</a> |
							<a href="https://www.lightbend.com/legal/privacy" target="_blank">Privacy Policy</a> |
							<a href="https://akka.io/cookie/" target="_blank">Cookie Listing</a> |
							<a class="optanon-toggle-display">Cookie Settings</a>
						</p>
					</section>
