<div id="lightbend-banner" class="lightbend-banner akka full-width" data-category="OSS Lightbend Banner Impression" data-label="Akka Banner Impression">
	<div class="oss-wrapper">
		<div class="oss-brand">
			<a class="oss-track-link-label" data-category="OSS Lightbend Banner Clicks" data-label="Lightbend Logo - Akka Banner" href="https://www.lightbend.com">
				<img class="lightbend-logo" src="$page.base$images/banner-logos/lightbend-reverse.svg" alt="Lightbend" title="Lightbend">
			</a>
		</div>
		<div class="oss-ad no-drop-down">
			<nav id="lightbendRotator" class="lightbend-rotator">
				<a class="oss-track-link-label" data-category="OSS Lightbend Banner Clicks" data-label="Promo Rotator - Akka Serverless Open Beta - Keep the data. Lose the database. Try now for free. [Learn More] - Akka Banner" href="https://www.lightbend.com/akka-serverless">
					<strong>Akka Serverless Open Beta</strong> - Keep the data. Lose the database. Try now for free. <span class="akka-btn">Learn More</span>
				</a>
				<a class="oss-track-link-label" data-category="OSS Lightbend Banner Clicks" data-label="Promo Rotator - Using AWS or GCP? Simplify deployments with Akka Cloud Platform [Learn More] - Akka Banner" href="https://www.lightbend.com/akka-cloud-platform">
					<strong>Using AWS or GCP?</strong>&nbsp;&nbsp;Simplify deployments with Akka Cloud Platform. <span class="akka-btn">Learn More</span>
				</a>
			</nav>
		</div>
	</div>
</div>