<div id="lightbend-banner" class="lightbend-banner akka full-width" data-category="OSS Lightbend Banner Impression" data-label="Akka Banner Impression">
	<div class="oss-wrapper">
		<div class="oss-brand">
			<a class="oss-track-link-label" data-category="OSS Lightbend Banner Clicks" data-label="Lightbend Logo - Akka Banner" href="https://www.lightbend.com">
				<img class="lightbend-logo" src="$page.base$images/banner-logos/lightbend-reverse.svg" alt="Lightbend" title="Lightbend">
			</a>
		</div>
		<div class="oss-ad no-drop-down">
			<nav id="lightbendRotator" class="lightbend-rotator">
				<a class="oss-track-link-label" data-category="OSS Lightbend Banner Clicks" data-label="Promo Rotator - Kalix - High-performance microservices and APIs with no operations required. - Akka Banner" href="https://www.kalix.io/">
					<strong>Kalix</strong> - High-performance microservices and APIs with no operations required. <span class="akka-btn">Learn More</span>
				</a>
				<a class="oss-track-link-label" data-category="OSS Lightbend Banner Clicks" data-label="Promo Rotator - Meet Akka Insights! A stand alone telemetry & observability offering. [Learn More] - Akka Banner" href="https://www.lightbend.com/akka-insights">
					<strong>Meet Akka Insights!</strong>&nbsp;&nbsp;A stand alone telemetry & observability offering. <span class="akka-btn">Learn More</span>
				</a>
			</nav>
		</div>
	</div>
</div>
