<div id="lightbend-banner" class="lightbend-banner akka full-width" data-category="OSS Lightbend Banner Impression" data-label="Akka Banner Impression">
	<div class="oss-wrapper">
		<div class="oss-brand">
			<a class="oss-track-link-label" data-category="OSS Lightbend Banner Clicks" data-label="Lightbend Logo - Akka Banner" href="https://www.lightbend.com">
				<img class="lightbend-logo" src="$page.base$images/banner-logos/lightbend-reverse.svg" alt="Lightbend" title="Lightbend">
			</a>
		</div>
		<div class="oss-ad no-drop-down">
			<nav id="lightbendRotator" class="lightbend-rotator">
				<a class="oss-track-link-label" data-category="OSS Lightbend Banner Clicks" data-label="Promo Rotator - Introducing Akka Cloud to Edge Continuum. Build once for the Cloud. Seamlessly deploy to the Edge. [Learn more] - Akka Banner" href="https://www.lightbend.com/blog/akka-edge-unifying-the-cloud-and-edge">
					Introducing Akka Cloud to Edge Continuum. Build once for the Cloud. Seamlessly deploy to the Edge. <span class="akka-btn">Learn more</span>
				</a>
			</nav>
		</div>
	</div>
</div>
